# Deploy the pods
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: catalogue-deployment
spec:
  selector:
    matchLabels:
      app: catalogue
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
      - name: catalogue
        image: 770817924447.dkr.ecr.us-east-2.amazonaws.com/catalogue:v1
        ports:
        - containerPort: 9090
---
# This service is used to expose the pods on a port
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    app: catalogue
  ports:
    - port: 9090
      protocol: TCP